### ISSUE TITLE
Where is the location of "DATA" directory?

### ISSUE THREAD

**Issue by herleeyandi** [MarvinTeichmann/MultiNet#17]
I have try the demo and it stuck because of missing `DATA/weight/vgg16.npy `then I just download from another source. I just create `DATA` directory inside of  `Multinet `(root) directory, so it becomes `Multinet/DATA/weights/vgg16.npy` but still it not found. So I just choose download it using your download script. Now I am in managing my directory space, so, where is `DATA` location? After finish download wherecan I find `DATA` ?

**Comment by MarvinTeichmann** [comment]
Data dir is controlled by the environoment Variable `$TV_DIR_DATA`. Use

`export TV_DIR_DATA="/MY/LARGE/HDD/DATA"`

To set the directory appropriatly.

With respect to VGG weights there is currently a minor bug. You need VGG weights in both dirs `DATA/weights/vgg16.npy` and `DATA/vgg16.npy`. Use symlink to archive this.
