### ISSUE TITLE
Resource exhausted/ran out of memory trying to allocate while training

### ISSUE THREAD

**Issue by PSathyaBhat** [MarvinTeichmann/MultiNet#18]
Hi, I am trying to run the train.py code as explained in README file. I am getting the following error.

_$ python train.py --hypes hypes/multinet2.json_
[I have added parts of the output log relevant here]  
_I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: GeForce GTX 980 Ti
major: 5 minor: 2 memoryClockRate (GHz) 1.2405
pciBusID 0000:01:00.0
Total memory: 5.93GiB
Free memory: 5.70GiB_

_W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 245.00MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 278.55MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available.
W tensorflow/core/common_runtime/bfc_allocator.cc:217] Ran out of memory trying to allocate 4.00MiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory is available._

_I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 5.40GiB
I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                  5804326912
InUse:                  5803421440
MaxInUse:               5803589120
NumAllocs:                     719
MaxAllocSize:           1270318592_

_W tensorflow/core/common_runtime/bfc_allocator.cc:274] 
W tensorflow/core/common_runtime/bfc_allocator.cc:275] Ran out of memory trying to allocate 2.25MiB.  See logs for memory state.
W tensorflow/core/framework/op_kernel.cc:993] Resource exhausted: OOM when allocating tensor with shape[256,256,3,3]
W tensorflow/core/kernels/queue_base.cc:294] _0_Queues_segmentation/fifo_queue: Skipping cancelled enqueue attempt with queue not closed
W tensorflow/core/kernels/queue_base.cc:294] _1_Queues_detection/fifo_queue: Skipping cancelled enqueue attempt with queue not closed_

I thought I need to adjust the Batch_Size value in hypes/multinet2.json, but even at a value of 1 the training fails.
What could be the reason?

**Comment by MarvinTeichmann** [comment]
GPU Memory. You need 12 GB to train MultiNet with VGG encoder on full resolution and 16 GB for MultiNet with Resnet encoder. You can use patch training or resize the images to train on lower resolution.

**Comment by xiaofeiwu** [comment]
a follow up question, is it possible to run the training with multiple GPU, while each one of them has a smaller memory, for instance, 6GB * 2/3 GPUs. I tried it with: 
`python train.py --hypes hypes/multinet2.json --gpus 0,1,2`
but still run out of memory
