### ISSUE TITLE
Some submodules issues

### ISSUE THREAD

**Issue by lbin** [MarvinTeichmann/MultiNet#2]
Hi @MarvinTeichmann 

Thanks for releasing these codes again!

I found some issues about submodules and report here:
1. I think you may forget to submit the ref of the submodules, especially TensorVision
2. The TensorVision's version is not right, so I put kittiseg's tensorvision into this projects
Now the train.py could run and I will check the final results.

Thanks again~

**Comment by MarvinTeichmann** [comment]
Are you sure? 81644b23b22cb192a590543094a4b928a711d3b8 should be the right tensorvision version. Master on the other hand is not compatible, yet.

**Comment by lbin** [comment]
It is very strange, my tensorvision is on `master` branch. Anyway, the training process could be run.

**Comment by lbin** [comment]
I may find the problem: when I open the website `https://github.com/TensorVision/TensorVision`, I only could see **97** commits, but I could see **118** commit via submodule/TensorVision.
Are these commits private?

**Comment by MarvinTeichmann** [comment]
No, the master branch contains squash commits.

**Comment by lbin** [comment]
I solved this issue by `pip install https://github.com/TensorVision/TensorVision/archive/master.zip`.

**Comment by lbin** [comment]
It is my fault.
I used `git clone git@github.com:MarvinTeichmann/MultiNet.git` and I should use `git clone https://github.com/MarvinTeichmann/MultiNet.git`
I will close this issue.
