### ISSUE TITLE
the detection time is too long.

### ISSUE THREAD

**Issue by wumengfei** [MarvinTeichmann/MultiNet#20]
As the paper says,  MultiNet could do the detection within 100ms. However, the time used is 5 seconds long. How could it be?

**Comment by MarvinTeichmann** [comment]
I suspect you are measuring the runtime of demo.py? In this case you have quite a bit of overhead as the graph is only compiled in the first run and visualization is part of demo.py. Please use [predict_joint.py](https://github.com/MarvinTeichmann/MultiNet/blob/master/predict_joint.py) to measure runtime. Also have a look at the discussion [here](https://github.com/MarvinTeichmann/KittiBox/issues/15).

**Comment by wumengfei** [comment]
Thanks a lot~
--
Mengfei,Wu
School of Information and Communication Engineering,
Beijing University of Posts and Telecommunications(BUPT)
Mobile:+86-18311016018

**Comment by MarvinTeichmann** [comment]
Fixed in 5f16480bcc94de0bbd33cb7dedcb89b4fc136c36.
