### ISSUE TITLE
Using multiple GPU for training

### ISSUE THREAD

**Issue by debapriyamaji** [MarvinTeichmann/MultiNet#44]
@MarvinTeichmann 
I have three GPUs in my system. However, the program is using only one of them. Even though it greedily captures all the memory, it uses the computational power of a single GPU.

Is there a fix for this?

**Comment by MarvinTeichmann** [comment]
Yes, follow this steps: https://www.tensorflow.org/programmers_guide/using_gpu#using_multiple_gpus

**Comment by jingweike** [comment]
Thanks! Also want to see this after that one:

6209 Everglades Dr, Alexandria, VA 22312 - 4 beds/3.5 baths


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
6209 Everglades Dr, Alexandria, VA 22312 - 4 beds/3.5 baths

(MRIS) For Sale: 4 bed, 3.5 bath ∙ 3500 sq. ft. ∙ 6209 Everglades Dr, Alexandria, VA 22312 ∙ $800,000 ∙ MLS# FX1...
 |

 |

 |




    On Thursday, May 10, 2018, 9:39:44 PM EDT, Marvin Teichmann <notifications@github.com> wrote:  
 
 
Yes, follow this steps: https://www.tensorflow.org/programmers_guide/using_gpu#using_multiple_gpus
