### ISSUE TITLE
error in Initialize all submodules

### ISSUE THREAD

**Issue by zdx3578** [MarvinTeichmann/MultiNet#5]
ubuntu@ip-172-30-5-78:~/zdx/MultiNet$ git submodule update --init --recursive
fatal: reference is not a tree: 81644b23b22cb192a590543094a4b928a711d3b8
Unable to checkout '81644b23b22cb192a590543094a4b928a711d3b8' in submodule path 'submodules/KittiBox/submodules/TensorVision'
fatal: reference is not a tree: 81644b23b22cb192a590543094a4b928a711d3b8
Unable to checkout '81644b23b22cb192a590543094a4b928a711d3b8' in submodule path 'submodules/KittiClass/submodules/TensorVision'
fatal: reference is not a tree: 81644b23b22cb192a590543094a4b928a711d3b8
Unable to checkout '81644b23b22cb192a590543094a4b928a711d3b8' in submodule path 'submodules/KittiSeg/submodules/TensorVision'
fatal: reference is not a tree: 81644b23b22cb192a590543094a4b928a711d3b8
Failed to recurse into submodule path 'submodules/KittiBox'
Failed to recurse into submodule path 'submodules/KittiClass'
Failed to recurse into submodule path 'submodules/KittiSeg'
Unable to checkout '81644b23b22cb192a590543094a4b928a711d3b8' in submodule path 'submodules/TensorVision'

**Comment by maxtom** [comment]
Same problem, any solution ?

**Comment by maxtom** [comment]
@zdx3578 
It's the TrensorVision error, I fix the problem by 
pip install https://github.com/TensorVision/TensorVision/archive/master.zip.

**Comment by zdx3578** [comment]
this 81644b23b22cb192a590543094a4b928a711d3b8  some error;

**Comment by lizhaoda** [comment]
@maxtom  After that step,should I  do "git submodule update --init --recursive"?

**Comment by MarvinTeichmann** [comment]
Did #7 fix this?
