### ISSUE TITLE
The kitti download url is not accessible now, can not finish running download_data.py

### ISSUE THREAD

**Issue by Aestheticism1** [MarvinTeichmann/MultiNet#62]
and when i run 'python demo.py --gpus 0 --input data/demo/um_000005.png'.

**Comment by Aestheticism1** [comment]
'ERROR File 'DATA/weights/vgg16.npy' not found. Download it from https://dl.dropboxusercontent.com/u/50333326/vgg16.npy'

i have got the 'data_road.zip' in another way, how can i figure this out and successfully run 'demo.py' now?

if you see my question and give a simple response, i would be most grateful.

**Comment by Aestheticism1** [comment]
sry. it's because of my network. now it can work.

**Comment by xuchen-dev** [comment]
> sry. it's because of my network. now it can work.

hi ， could you provide  me with the pretrain model and the vgg16
